// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1bvsdmm45RG91JN6zGwk2mwTlbz8e5I',
    appId: '1:448842972248:android:e0c8beffb74d943d071e2d',
    messagingSenderId: '448842972248',
    projectId: 'todolist-87b0d',
    storageBucket: 'todolist-87b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqY_O0Olh3dezSYpi7rlXCSZSOeXyjJB4',
    appId: '1:448842972248:ios:5426ed4eaff768e9071e2d',
    messagingSenderId: '448842972248',
    projectId: 'todolist-87b0d',
    storageBucket: 'todolist-87b0d.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqY_O0Olh3dezSYpi7rlXCSZSOeXyjJB4',
    appId: '1:448842972248:ios:a9bd5bcedac70910071e2d',
    messagingSenderId: '448842972248',
    projectId: 'todolist-87b0d',
    storageBucket: 'todolist-87b0d.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
